### PR TITLE
[SMHTT2017-dev] Merge changes from KIT

### PR DESCRIPTION
**Pull request by stwunsch**
@mflechl We've put in following changes:

1. Remove EWKZ process (merged to DY)
2. Introduce TTL and VVL process splitting
3. Set lumi uncertainty for 2017
4. Decorrelate trigger efficiency for embedding
5. Partially correlate tau ID efficiency for embedding
6. Add recoil correction uncertainties
7. Remove decay mode dependent lepton to tau fake rates and implement log-normal uncertainties such as recommended

### CODE REVIEW

**Comment by stwunsch** [comment]
@swozniewski @janekbechtel fyi

**Comment by mflechl** [comment]
Thanks!

Concerning correlations between MC- and embedding processes for several uncertainties:
- what you implemented now: there is an uncertainty for MC which is 100% correlated to half of the embedded uncertainty, and the other half of the embedded uncertainty is uncorrelated (to MC).
Are you sure this is what you want? Or would you not rather want
- alternative: half the uncertainty for MC is 100% correlated to half of the embedded uncertainty: the other half of the embedded uncertainty is uncorrelated (to MC), and the other half of the MC uncertainty is uncorrelated (to EMB)?

**Comment by janekbechtel** [comment]
Hi Martin,

you were right, we intended your second point. I implemented the changes, could you please check if it is correct now?
Thanks!
Janek

**Comment by mflechl** [comment]
Thanks, this aspect looks fine now.

However, in line 287 (scale_mc_e), the value should *not* be sqrt(2)=1.41, but instead 1/sqrt(2)=0.71, isn't it?
The same is true for several other lines for e scale and tau scale.

Thanks,
Martin

**Comment by janekbechtel** [comment]
Hi Martin, 
our understanding is that the value given determines to how many sigma the given shape corresponds to, just as the 1sigma shift is given for lnN uncertainties. I could not really find a documentation about this though which validates this, if you remember it otherwise we should confirm it.
Thanks,
Janek

**Comment by mflechl** [comment]
Hi Janek,

See here:
https://cms-hcomb.gitbooks.io/combine/content/part2/settinguptheanalysis.html#binned-shape-analysis
and scroll down to "sigma  shape    0.5"

According to this, it is the other way round - the value "renormalises the input histo", i.e. is the inverse of the shift given (in sigmas). So, in analogy to this, we want the histogram to now represent a sqrt(2) sigma variation, so the number should be 1/sqrt(2).

We should probably eventually confirm this nonetheless (i.e. mail to the combination hypernews), but I think for now we can assume the documentation is correct.

Cheers,
Martin

**Comment by janekbechtel** [comment]
Hi Martin, thanks for finding this so fast, you are correct! I changed the values to 1/sqrt(2)

**Pull request merged**
